- src/main/java/ch/heigvd/res/pizza/domain/panticne/PizzaKebab.java
- src/test/java/ch/heigvd/res/pizza/domain/panticne/PizzaKebabTest.java
> Add PizzaKebab with tests

- src/main/java/ch/heigvd/res/pizza/domain/edinem/Diavolo.java
- src/test/java/ch/heigvd/res/pizza/domain/edinem/DiavoloTest.java
added diavolo pizza. Tests ok. closes #45
> adding diavolo pizza

- src/main/java/ch/heigvd/res/pizza/domain/Ichimizu/Yolo.java
- src/test/java/ch/heigvd/res/pizza/domain/Ichimizu/YoloTest.java
> Add Yolo with tests

- src/main/java/ch/heigvd/res/pizza/domain/victortruan/Thon.java
- src/test/java/ch/heigvd/res/pizza/domain/victortruan/ThonTest.java
> Ajout de la pizza au thon

- src/main/java/ch/heigvd/res/pizza/domain/Crulllo/ChevreMiel.java
- src/test/java/ch/heigvd/res/pizza/domain/Crulllo/ChevreMielTest.java
> Add ChevreMiel

- src/main/java/ch/heigvd/res/pizza/domain/Ezehkiel/Calson.java
- src/test/java/ch/heigvd/res/pizza/domain/Ezehkiel/CalsonTest.java
> Added Calson with test

- src/main/java/ch/heigvd/res/pizza/domain/linois/Margherita.java
- src/test/java/ch/heigvd/res/pizza/domain/linois/MargheritaTest.java
> Added margherita with tests

- src/main/java/ch/heigvd/res/pizza/domain/boosterloop/Romana.java
- src/test/java/ch/heigvd/res/pizza/domain/boosterloop/RomanaTest.java
> Added Romana with tests

- src/main/java/ch/heigvd/res/pizza/domain/isaiaSpinelli/FirstPesto.java
- src/test/java/ch/heigvd/res/pizza/domain/isaiaSpinelli/FirstPestoTest.java
> Add first pizza FirstPesto

- src/main/java/ch/heigvd/res/pizza/domain/oTwoWin/Napolitan.java
- src/test/java/ch/heigvd/res/pizza/domain/oTwoWin/NapolitanTest.java
> Fb napolitan pizza

- src/main/java/ch/heigvd/res/pizza/domain/goturak/Hawai.java
- src/test/java/ch/heigvd/res/pizza/domain/goturak/HawaiTest.java
> Added and tested Hawai

- src/main/java/ch/heigvd/res/pizza/domain/SamuelMettler/NomUnique.java
- src/test/java/ch/heigvd/res/pizza/domain/SamuelMettler/NomUniqueTest.java
> Add NomUnique with test

- src/main/java/ch/heigvd/res/pizza/domain/mtutic/Jambon.java
- src/test/java/ch/heigvd/res/pizza/domain/mtutic/JambonTest.java
> Add jambon with tests

- src/main/java/ch/heigvd/res/pizza/domain/andresMoreno96/ANDY.java
- src/test/java/ch/heigvd/res/pizza/domain/andresMoreno96/ANDYTest.java
> andy pizza added

- src/main/java/ch/heigvd/res/pizza/domain/jackeri/Calzone.java
- src/test/java/ch/heigvd/res/pizza/domain/jackeri/CalzoneTest.java
> Calzone + tests

- src/main/java/ch/heigvd/res/pizza/domain/MarionDL/FourSeasons.java
- src/test/java/ch/heigvd/res/pizza/domain/MarionDL/FourSeasonsTest.java
> Added new pizza Four Seasons

- src/main/java/ch/heigvd/res/pizza/domain/gaeba95/Banana.java
- src/test/java/ch/heigvd/res/pizza/domain/gaeba95/BananaTest.java
> Adding banana

- src/main/java/ch/heigvd/res/pizza/domain/Laykel/Salmone.java
- src/test/java/ch/heigvd/res/pizza/domain/Laykel/SalmoneTest.java
> Added salmone pizza for treats from the Sea

- src/main/java/ch/heigvd/res/pizza/domain/capito27/Hawai.java
- src/test/java/ch/heigvd/res/pizza/domain/capito27/HawaiTest.java
> Add Hawai with tests

- src/main/java/ch/heigvd/res/pizza/domain/nathanseville/Fourseasons.java
- src/test/java/ch/heigvd/res/pizza/domain/nathanseville/FourseasonsTest.java
I've implemented the 4 seasons pizza. Closes #52
> new pizza 4seasons

- src/main/java/ch/heigvd/res/pizza/domain/Dherleth/PapaJohnsPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/Dherleth/PapaJohnsPizzaTest.java
> Added a Papa John's Pizza

- src/main/java/ch/heigvd/res/pizza/domain/kaerdhalis/RedPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/kaerdhalis/RedPizzaTest.java
> add redpizza

- src/main/java/ch/heigvd/res/pizza/domain/joshuaGomesDaCosta/Hawai.java
- src/test/java/ch/heigvd/res/pizza/domain/joshuaGomesDaCosta/HawaiTest.java
> Hawai with test

- src/main/java/ch/heigvd/res/pizza/domain/GODOmegaPi/Ananas.java
- src/test/java/ch/heigvd/res/pizza/domain/GODOmegaPi/AnanasTest.java
> Added a new ananas pizza with tests

- src/main/java/ch/heigvd/res/pizza/domain/mercierjo/JosPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/mercierjo/JosPizzaTest.java
> Add JosPizza and tests

- src/main/java/ch/heigvd/res/pizza/domain/lapinousexy/Margarita.java
- src/test/java/ch/heigvd/res/pizza/domain/lapinousexy/MargaritaTest.java
> Added Margarita

- src/main/java/ch/heigvd/res/pizza/domain/Thorkal/Calzone.java
- src/test/java/ch/heigvd/res/pizza/domain/Thorkal/CalzoneTest.java
> Added Calzone with tests

- src/main/java/ch/heigvd/res/pizza/domain/Koffi94/Calzone.java
- src/test/java/ch/heigvd/res/pizza/domain/Koffi94/CalzoneTest.java
> Add new Calzone

- src/main/java/ch/heigvd/res/pizza/domain/RobelT/Salami.java
- src/test/java/ch/heigvd/res/pizza/domain/RobelT/SalamiTest.java
> Pizza Salami

- src/main/java/ch/heigvd/res/pizza/domain/capito27/Calzone.java
- src/test/java/ch/heigvd/res/pizza/domain/capito27/CalzoneTest.java
> Add Calzone with tests

- src/main/java/ch/heigvd/res/pizza/domain/Jael24/Capricciosa.java
- src/test/java/ch/heigvd/res/pizza/domain/Jael24/CapricciosaTest.java
> Added Capricciosa

- src/main/java/ch/heigvd/res/pizza/domain/gvetter/Napolita.java
- src/test/java/ch/heigvd/res/pizza/domain/gvetter/NapolitaTest.java
> Adding Napolita pizza

- src/main/java/ch/heigvd/res/pizza/domain/pagedidier/Diavola.java
- src/test/java/ch/heigvd/res/pizza/domain/pagedidier/DiavolaTest.java
Closes  #14
I added the Diavola pizza and his tests
> Ajout de la pizza Diavola et ses tests

- src/main/java/ch/heigvd/res/pizza/domain/Tsimwi/AnanasPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/Tsimwi/AnanasPizzaTest.java
> Add ananaspizza

- src/main/java/ch/heigvd/res/pizza/domain/ercclpn/SpicyPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/ercclpn/SpicyPizzaTest.java
Please have a look at my code, should close #18
> Add spicy pizza and tests

- src/main/java/ch/heigvd/res/pizza/domain/Ichimizu/Funky.java
- src/test/java/ch/heigvd/res/pizza/domain/Ichimizu/FunkyTest.java
> Add funky with tests

- src/main/java/ch/heigvd/res/pizza/domain/panticne/PizzaGainzz.java
- src/test/java/ch/heigvd/res/pizza/domain/panticne/PizzaGainzzTest.java
> Add PizzaGainzz with tests

- src/main/java/ch/heigvd/res/pizza/domain/mbonjour/Chorizo.java
- src/test/java/ch/heigvd/res/pizza/domain/mbonjour/ChorizoTest.java
This closes #77 
Here is the fabulous Chorizo Pizza !
> added chorizo

- src/main/java/ch/heigvd/res/pizza/domain/nyg/Hawaii.java
- src/test/java/ch/heigvd/res/pizza/domain/nyg/HawaiiTest.java
> Adding Hawaii pizza

- src/main/java/ch/heigvd/res/pizza/domain/playjul306/Pepperoni.java
- src/test/java/ch/heigvd/res/pizza/domain/playjul306/PepperoniTest.java
> add a Pepperoni

- src/main/java/ch/heigvd/res/pizza/domain/Cell00phane/Funghi.java
- src/test/java/ch/heigvd/res/pizza/domain/Cell00phane/FunghiTest.java
> Add Funghi

- src/main/java/ch/heigvd/res/pizza/domain/sjaubain/PizzaEco.java
- src/test/java/ch/heigvd/res/pizza/domain/sjaubain/PizzaEcoTest.java
> add pizza eco with tests

- src/main/java/ch/heigvd/res/pizza/domain/goturak/Trex.java
- src/test/java/ch/heigvd/res/pizza/domain/goturak/TrexTest.java
> added and tested Trex

- src/main/java/ch/heigvd/res/pizza/domain/mullerPierrickHeig/Crudo.java
- src/test/java/ch/heigvd/res/pizza/domain/mullerPierrickHeig/CrudoTest.java
> Ajout de la pizza Crudo avec tests

- src/main/java/ch/heigvd/res/pizza/domain/XBrast/Thon.java
- src/test/java/ch/heigvd/res/pizza/domain/XBrast/ThonTest.java
> ajout de l'ingrédient thon

- src/main/java/ch/heigvd/res/pizza/domain/NatMiz/Royale.java
- src/test/java/ch/heigvd/res/pizza/domain/NatMiz/RoyaleTest.java
> Add Royale with tests

- src/main/java/ch/heigvd/res/pizza/domain/jerozerbib/Thuna.java
- src/test/java/ch/heigvd/res/pizza/domain/jerozerbib/ThunaTest.java
> Ajout de Thuna

- src/main/java/ch/heigvd/res/pizza/domain/isaiaSpinelli/BananaPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/isaiaSpinelli/BananaPizzaTest.java
> Add second pizza BananaPizza

- src/main/java/ch/heigvd/res/pizza/domain/zereddiamond/Etna.java
- src/test/java/ch/heigvd/res/pizza/domain/zereddiamond/EtnaTest.java
> Added new pizza Etna

- src/main/java/ch/heigvd/res/pizza/domain/CrescenceK/FruitMer.java
- src/test/java/ch/heigvd/res/pizza/domain/CrescenceK/FruitMerTest.java
> Add fuit de mer with tests

- src/main/java/ch/heigvd/res/pizza/domain/SamuelMettler/TresBonne.java
- src/test/java/ch/heigvd/res/pizza/domain/SamuelMettler/TresBonneTest.java
> Add pizza TresBonne with test

- src/main/java/ch/heigvd/res/pizza/domain/IxSysTech/Ananas.java
- src/test/java/ch/heigvd/res/pizza/domain/IxSysTech/AnanasTest.java
I have implemented the pizza ananas
> Add ananas

- src/main/java/ch/heigvd/res/pizza/domain/rafiibro/Rafii.java
- src/test/java/ch/heigvd/res/pizza/domain/rafiibro/RafiiTest.java
> Add rafii pizza

- src/main/java/ch/heigvd/res/pizza/domain/MichaelDaSilva/Raclette.java
- src/test/java/ch/heigvd/res/pizza/domain/MichaelDaSilva/RacletteTest.java
> Add pizza raclette 

- src/main/java/ch/heigvd/res/pizza/domain/MarionDL/Carnivore.java
- src/test/java/ch/heigvd/res/pizza/domain/MarionDL/CarnivoreTest.java
> Added Carnivore pizza with tests

- src/main/java/ch/heigvd/res/pizza/domain/boosterloop/Chorizo.java
- src/test/java/ch/heigvd/res/pizza/domain/boosterloop/ChorizoTest.java
> Added Chorizo with tests

- src/main/java/ch/heigvd/res/pizza/domain/waltharnack/Calabrese.java
- src/test/java/ch/heigvd/res/pizza/domain/waltharnack/CalabreseTest.java
> Add calabrese

- src/main/java/ch/heigvd/res/pizza/domain/naetheline/HawaiPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/naetheline/HawaiPizzaTest.java
> Adding Hawai pizza test and impl

- src/main/java/ch/heigvd/res/pizza/domain/Obyka/PizzaNutella.java
- src/test/java/ch/heigvd/res/pizza/domain/Obyka/PizzaNutellaTest.java
> nutella implemented

- src/main/java/ch/heigvd/res/pizza/domain/StefanDejanovicHeig/PizzaJambon.java
- src/test/java/ch/heigvd/res/pizza/domain/StefanDejanovicHeig/PizzaJambonTest.java
> Add pizza jambon

- src/main/java/ch/heigvd/res/pizza/domain/lapinousexy/QuatreFromages.java
- src/test/java/ch/heigvd/res/pizza/domain/lapinousexy/QuatreFromagesTest.java
> Added QuatreFromages

- src/main/java/ch/heigvd/res/pizza/domain/kaerdhalis/YellowPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/kaerdhalis/YellowPizzaTest.java
> add yellowpizza

- src/main/java/ch/heigvd/res/pizza/domain/oTwoWin/Portuguese.java
- src/test/java/ch/heigvd/res/pizza/domain/oTwoWin/PortugueseTest.java
> Added pizza Portuguese

- src/main/java/ch/heigvd/res/pizza/domain/gaeba95/Chocolate.java
- src/test/java/ch/heigvd/res/pizza/domain/gaeba95/ChocolateTest.java
> Adding chocolate

- src/main/java/ch/heigvd/res/pizza/domain/petit1suisse/Alexza.java
- src/test/java/ch/heigvd/res/pizza/domain/petit1suisse/AlexzaTest.java
I've add ALexza pizza in package petit1suisse. 
Have a nice day
> add alexza

- src/main/java/ch/heigvd/res/pizza/domain/RobelT/Chicken.java
- src/test/java/ch/heigvd/res/pizza/domain/RobelT/ChickenTest.java
> Pizza Chicken

- src/main/java/ch/heigvd/res/pizza/domain/texx94/Jambon.java
- src/test/java/ch/heigvd/res/pizza/domain/texx94/JambonTest.java
> Pizza jambon dispo

- src/main/java/ch/heigvd/res/pizza/domain/Ezehkiel/Nutella.java
- src/test/java/ch/heigvd/res/pizza/domain/Ezehkiel/NutellaTest.java
I'm done with this pizza and it close #121
> Added pizza nutella with test

- src/main/java/ch/heigvd/res/pizza/domain/ercclpn/SuperHotPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/ercclpn/SuperHotPizzaTest.java
Please have a look at my code, should close #40 .
> Add super hot pizza and test

- src/main/java/ch/heigvd/res/pizza/domain/Laykel/Beef.java
- src/test/java/ch/heigvd/res/pizza/domain/Laykel/BeefTest.java
> Added beef pizza, because beef

- src/main/java/ch/heigvd/res/pizza/domain/tatallias/BellaItalia.java
- src/test/java/ch/heigvd/res/pizza/domain/tatallias/BellaItaliaTest.java
> Add BellaItalia with tests

- src/main/java/ch/heigvd/res/pizza/domain/nathanseville/Napolitan.java
- src/test/java/ch/heigvd/res/pizza/domain/nathanseville/NapolitanTest.java
I've implemented the napolitan pizza. Closes #167
> Implementation of the napolitan pizza

- src/main/java/ch/heigvd/res/pizza/domain/jackeri/Montagnarde.java
- src/test/java/ch/heigvd/res/pizza/domain/jackeri/MontagnardeTest.java
> Montagnarde + tests

- src/main/java/ch/heigvd/res/pizza/domain/mercierjo/Banana.java
- src/test/java/ch/heigvd/res/pizza/domain/mercierjo/BananaTest.java
> Add pizza banana with tests

- src/main/java/ch/heigvd/res/pizza/domain/GODOmegaPi/Apple.java
- src/test/java/ch/heigvd/res/pizza/domain/GODOmegaPi/AppleTest.java
> adding new apple pizza

- src/main/java/ch/heigvd/res/pizza/domain/mbonjour/Chocolate.java
- src/test/java/ch/heigvd/res/pizza/domain/mbonjour/ChocolateTest.java
I'v added Chocolate but don't know why
This closes #190
> added chocolate

- src/main/java/ch/heigvd/res/pizza/domain/XBrast/Tomato.java
- src/test/java/ch/heigvd/res/pizza/domain/XBrast/TomatoTest.java
> ajout de la tomate

- src/main/java/ch/heigvd/res/pizza/domain/playjul306/Tunisian.java
- src/test/java/ch/heigvd/res/pizza/domain/playjul306/TunisianTest.java
we add a Tunisian. closes #205
> add a Tunisian

- src/main/java/ch/heigvd/res/pizza/domain/Dherleth/VegiPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/Dherleth/VegiPizzaTest.java
> Added a little vegi

- src/main/java/ch/heigvd/res/pizza/domain/jzaehrin/Calabres.java
- src/test/java/ch/heigvd/res/pizza/domain/jzaehrin/CalabresTest.java
> Add Calabres Pizza

- src/main/java/ch/heigvd/res/pizza/domain/mullerPierrickHeig/Crudo2.java
- src/test/java/ch/heigvd/res/pizza/domain/mullerPierrickHeig/Crudo2Test.java
> Ajout crudo2 with tests

- src/main/java/ch/heigvd/res/pizza/domain/Jostoph/Diabolo.java
- src/test/java/ch/heigvd/res/pizza/domain/Jostoph/DiaboloTest.java
> Add Diabolo pizza with basic tests

- src/main/java/ch/heigvd/res/pizza/domain/RengokuryuuHonokaCrimsonFlame/PizzaP.java
- src/test/java/ch/heigvd/res/pizza/domain/RengokuryuuHonokaCrimsonFlame/PizzaPTest.java
> Ceci est un test

- src/main/java/ch/heigvd/res/pizza/domain/nyg/Pepperoni.java
- src/test/java/ch/heigvd/res/pizza/domain/nyg/PepperoniTest.java
> Add pepperoni

- src/main/java/ch/heigvd/res/pizza/domain/Thorkal/Paysanne.java
- src/test/java/ch/heigvd/res/pizza/domain/Thorkal/PaysanneTest.java
> Added Paysanne with tests

- src/main/java/ch/heigvd/res/pizza/domain/sjaubain/Pizza7fromages.java
- src/test/java/ch/heigvd/res/pizza/domain/sjaubain/Pizza7fromagesTest.java
> add pizza 7 fromages

- src/main/java/ch/heigvd/res/pizza/domain/jzaehrin/Hawai.java
- src/test/java/ch/heigvd/res/pizza/domain/jzaehrin/HawaiTest.java
> Add Hawai pizza

- src/main/java/ch/heigvd/res/pizza/domain/NatMiz/Teryaki.java
- src/test/java/ch/heigvd/res/pizza/domain/NatMiz/TeryakiTest.java
> Add Teryaki with tests

- src/main/java/ch/heigvd/res/pizza/domain/pete842/Brocoli.java
- src/test/java/ch/heigvd/res/pizza/domain/pete842/BrocoliTest.java
Add brocoli pizza with test
closes #219
> Add brocoli pizza with test

- src/main/java/ch/heigvd/res/pizza/domain/edinem/Jambon.java
- src/test/java/ch/heigvd/res/pizza/domain/edinem/JambonTest.java
Added jambon pizza. closes #91
> add jambon pizza

- src/main/java/ch/heigvd/res/pizza/domain/Cell00phane/Quatro.java
- src/test/java/ch/heigvd/res/pizza/domain/Cell00phane/QuatroTest.java
> Add Quatro

- src/main/java/ch/heigvd/res/pizza/domain/rafiibro/Boi.java
- src/test/java/ch/heigvd/res/pizza/domain/rafiibro/BoiTest.java
> Add Boi Pizza

- src/main/java/ch/heigvd/res/pizza/domain/waltharnack/Italia.java
- src/test/java/ch/heigvd/res/pizza/domain/waltharnack/ItaliaTest.java
> add italia

- src/main/java/ch/heigvd/res/pizza/domain/ecarpita93/Napoletana.java
- src/test/java/ch/heigvd/res/pizza/domain/ecarpita93/NapoletanaTest.java
> Implemented Napoletana

- src/main/java/ch/heigvd/res/pizza/domain/botebol/Calzone.java
- src/test/java/ch/heigvd/res/pizza/domain/botebol/CalzoneTest.java
> Fb calzone

- src/main/java/ch/heigvd/res/pizza/domain/texx94/Diabolo.java
- src/test/java/ch/heigvd/res/pizza/domain/texx94/DiaboloTest.java
> Diabolo dispo

- src/main/java/ch/heigvd/res/pizza/domain/joshuaGomesDaCosta/Season4.java
- src/test/java/ch/heigvd/res/pizza/domain/joshuaGomesDaCosta/Season4Test.java
> pizza 4season

- src/main/java/ch/heigvd/res/pizza/domain/lionelburgbach/Lard.java
- src/test/java/ch/heigvd/res/pizza/domain/lionelburgbach/LardTest.java
> Add Lard with test

- src/main/java/ch/heigvd/res/pizza/domain/Ichimizu/Satan.java
- src/test/java/ch/heigvd/res/pizza/domain/Ichimizu/SatanTest.java
> Add Satan with tests

- src/main/java/ch/heigvd/res/pizza/domain/pagedidier/Campagnard.java
- src/test/java/ch/heigvd/res/pizza/domain/pagedidier/CampagnardTest.java
> Add campagnard pizza

- src/main/java/ch/heigvd/res/pizza/domain/batach31/Piment.java
- src/test/java/ch/heigvd/res/pizza/domain/batach31/PimentTest.java
> Added piment

- src/main/java/ch/heigvd/res/pizza/domain/Jostoph/Thono.java
- src/test/java/ch/heigvd/res/pizza/domain/Jostoph/ThonoTest.java
> Add Thono with basic tests

- src/main/java/ch/heigvd/res/pizza/domain/ecarpita93/romana.java
- src/test/java/ch/heigvd/res/pizza/domain/ecarpita93/romanaTest.java
> Implemented romana

- src/main/java/ch/heigvd/res/pizza/domain/CrescenceK/Dynamite.java
- src/test/java/ch/heigvd/res/pizza/domain/CrescenceK/DynamiteTest.java
close #213 
j ai eu des pbs avec des captchas
> add dynamite with tests

- src/main/java/ch/heigvd/res/pizza/domain/Tsimwi/CenovisPizza.java
- src/test/java/ch/heigvd/res/pizza/domain/Tsimwi/CenovisPizzaTest.java
> Add Cenovis Pizza
